# Generated by Django 3.2 on 2022-12-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
    ]
