# Generated by Django 3.2 on 2022-12-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
