# Generated by Django 3.2 on 2022-12-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0007_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
